name: LFFSystem
main: keo\Main
version: 1.3.0
api: [5.0.0]
author: Keole
website: https://github.com/keolehub

commands:
  lff:
    description: buscar una facción.
    usage: /lff
    permission: lff.command

permissions:
  lff.command:
    description: Permite usar el comando /lff
    default: true